# This is a basic workflow to help you get started with Actions

name: argo-update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 
      - 'Dockerfile'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Export tag version
        run: |
          latest_tag="v0.0.9"
          echo "ltag=$latest_tag" >> $GITHUB_ENV
      - name: Run a multi-line script
        run: |
          echo "new tag version tag-${{ env.ltag }}"        
      - uses: actions/checkout@master
        with:
          repository: karthick-kk/argo-githubrunner
          token: ${{ secrets.GITKEN }}
      - name: Update deployment image version of k8
        run: |
          sed -i 's/\(github-runner:\).*/\1'"$ltag"'/g' runner.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITKEN }}
          repository: karthick-kk/argo-githubrunner
          branch: ${{ github.ref }}
